$NAME_STR "Spacecraft Assembly Hall"

; Vostok, Voskhod, Soyuz and the lunar craft.

-------
$COST_WORK SOVIET_CONSTRUCTION_GROUNDWORKS 0.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO ground_asphalt 0.80
------------------
$COST_WORK SOVIET_CONSTRUCTION_SKELETON_CASTING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO wall_concrete 0.80
$COST_RESOURCE_AUTO wall_brick 0.30
------------------
$COST_WORK SOVIET_CONSTRUCTION_STEEL_LAYING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO tech_steel 0.50
-----------------------

$TYPE_FACTORY
$WORKERS_NEEDED 250
$PROFESORS_NEEDED 200
$PRODUCTION eletronics 0.0030
$CONSUMPTION plastics 0.0040
$CONSUMPTION fabric 0.0030
$CONSUMPTION food 0.0020
$CONSUMPTION_PER_SECOND eletric 0.40
$STORAGE_IMPORT_SPECIAL RESOURCE_TRANSPORT_COVERED 40 plastics
$STORAGE_IMPORT_SPECIAL RESOURCE_TRANSPORT_COVERED 40 fabric
$STORAGE_IMPORT_SPECIAL RESOURCE_TRANSPORT_COVERED 40 food
$STORAGE_EXPORT_SPECIAL RESOURCE_TRANSPORT_COVERED 60 eletronics

$VEHICLE_STATION 22.0 0.50 14.0  22.0 0.50 33.0
$VEHICLE_STATION 26.0 0.50 14.0  26.0 0.50 33.0
$VEHICLE_STATION 30.0 0.50 14.0  30.0 0.50 33.0

$CONNECTIONS_ROAD_DEAD_SQUARE
-45.0 -35.0
45.0 35.0

$CONNECTION_ROAD
0.0 0.0 36.5
0.0 0.0 35.0

$CONNECTION_PEDESTRIAN
8.0 0.0 36.5
8.0 0.0 35.0

end
