$NAME_STR "Landing and Recovery Field"

; Where the descent capsules come down in the steppe.

-------
$COST_WORK SOVIET_CONSTRUCTION_GROUNDWORKS 0.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO ground_asphalt 1.00
------------------
$COST_WORK SOVIET_CONSTRUCTION_SKELETON_CASTING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO wall_concrete 2.00
------------------
$COST_WORK SOVIET_CONSTRUCTION_STEEL_LAYING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO tech_steel 1.00
-----------------------

$TYPE_AIRPLANE_PARKING
$WORKING_VEHICLES_NEEDED 1
$HELIPORT_STATION 0.0 0.50 -9.0  0.0 0.50 9.0

$CONNECTIONS_AIRPORT_DEAD_SQUARE
-40.0 -40.0
40.0 40.0

$CONNECTION_ROAD
0.0 0.0 41.5
0.0 0.0 40.0

end
