$NAME_STR "Gagarin Monument"

; The first man in space.

$TYPE_MONUMENT
$MONUMENT_GOVERNMENT_LOYALTY_RADIUS 260
$MONUMENT_GOVERNMENT_LOYALTY_STRENGTH 3.2

-------
$COST_WORK SOVIET_CONSTRUCTION_GROUNDWORKS 0.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO ground_asphalt 0.50
------------------
$COST_WORK SOVIET_CONSTRUCTION_SKELETON_CASTING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO wall_concrete 1.50
------------------
$COST_WORK SOVIET_CONSTRUCTION_STEEL_LAYING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO tech_steel 0.60
-----------------------

$CONNECTION_PEDESTRIAN
0.0 0.0 21.5
0.0 0.0 20.0

end
