$NAME_STR "Rocket Plant (Progress)"

; Stage production, the Kuibyshev plant. Everything a rocket is made of meets here.

-------
$COST_WORK SOVIET_CONSTRUCTION_GROUNDWORKS 0.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO ground_asphalt 0.80
------------------
$COST_WORK SOVIET_CONSTRUCTION_SKELETON_CASTING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO wall_concrete 0.80
$COST_RESOURCE_AUTO wall_brick 0.30
------------------
$COST_WORK SOVIET_CONSTRUCTION_STEEL_LAYING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO tech_steel 0.50
-----------------------

$TYPE_FACTORY
$WORKERS_NEEDED 500
$PROFESORS_NEEDED 250
$PRODUCTION mcomponents 0.0040
$CONSUMPTION aluminium 0.0120
$CONSUMPTION steel 0.0080
$CONSUMPTION eletronics 0.0010
$CONSUMPTION_PER_SECOND eletric 0.40
$STORAGE_IMPORT_SPECIAL RESOURCE_TRANSPORT_OPEN 40 aluminium
$STORAGE_IMPORT_SPECIAL RESOURCE_TRANSPORT_OPEN 40 steel
$STORAGE_IMPORT_SPECIAL RESOURCE_TRANSPORT_COVERED 40 eletronics
$STORAGE_EXPORT_SPECIAL RESOURCE_TRANSPORT_COVERED 60 mcomponents

$VEHICLE_STATION -16.0 0.50 20.0  -16.0 0.50 50.0
$VEHICLE_STATION -12.0 0.50 20.0  -12.0 0.50 50.0
$VEHICLE_STATION -8.0 0.50 20.0  -8.0 0.50 50.0
$VEHICLE_STATION -4.0 0.50 20.0  -4.0 0.50 50.0

$CONNECTIONS_ROAD_DEAD_SQUARE
-85.0 -55.0
85.0 55.0

$CONNECTION_ROAD
0.0 0.0 56.5
0.0 0.0 55.0

$CONNECTION_PEDESTRIAN
8.0 0.0 56.5
8.0 0.0 55.0

end
