$NAME_STR "Propellant Plant (UDMH / N2O4)"

; Toxic hypergolic propellants for Proton and upper stages. Accidents happen.

-------
$COST_WORK SOVIET_CONSTRUCTION_GROUNDWORKS 0.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO ground_asphalt 0.80
------------------
$COST_WORK SOVIET_CONSTRUCTION_SKELETON_CASTING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO wall_concrete 0.80
$COST_RESOURCE_AUTO wall_brick 0.30
------------------
$COST_WORK SOVIET_CONSTRUCTION_STEEL_LAYING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO tech_steel 0.50
-----------------------

$TYPE_FACTORY
$WORKERS_NEEDED 90
$PROFESORS_NEEDED 30
$PRODUCTION chemicals 0.0300
$CONSUMPTION fuel 0.0150
$CONSUMPTION_PER_SECOND eletric 0.40
$STORAGE_IMPORT_SPECIAL RESOURCE_TRANSPORT_OIL 40 fuel
$STORAGE_EXPORT_SPECIAL RESOURCE_TRANSPORT_COVERED 60 chemicals
$POLLUTION_HIGH

$VEHICLE_STATION -6.0 0.50 22.0  -6.0 0.50 43.0
$VEHICLE_STATION -2.0 0.50 22.0  -2.0 0.50 43.0
$VEHICLE_STATION 2.0 0.50 22.0  2.0 0.50 43.0

$CONNECTIONS_ROAD_DEAD_SQUARE
-55.0 -45.0
55.0 45.0

$CONNECTION_ROAD
0.0 0.0 46.5
0.0 0.0 45.0

$CONNECTION_PEDESTRIAN
8.0 0.0 46.5
8.0 0.0 45.0

end
