$NAME_STR "Deep Space Tracking Station (Pluton)"

; Crewed flights and probes need the tracking network.

-------
$COST_WORK SOVIET_CONSTRUCTION_GROUNDWORKS 0.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO ground_asphalt 0.50
------------------
$COST_WORK SOVIET_CONSTRUCTION_SKELETON_CASTING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO wall_concrete 0.80
------------------
$COST_WORK SOVIET_CONSTRUCTION_STEEL_LAYING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO tech_steel 0.80
-----------------------

$TYPE_BROADCAST
$SUBTYPE_RADIO
$WORKERS_NEEDED 40
$PROFESORS_NEEDED 30
$CONSUMPTION_PER_SECOND eletric 1.5

$VEHICLE_STATION -4.0 0.50 28.0  -4.0 0.50 38.0
$VEHICLE_STATION 0.0 0.50 28.0  0.0 0.50 38.0

$CONNECTIONS_ROAD_DEAD_SQUARE
-50.0 -40.0
50.0 40.0

$CONNECTION_ROAD
-2.0 0.0 41.5
-2.0 0.0 40.0

$CONNECTION_PEDESTRIAN
6.0 0.0 41.5
6.0 0.0 40.0

end
